[package]
name = "lyra"
version = "0.1.0"
authors = ["dfontana <dyfontana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
keys = { path = "../keys" }
clap = "2.33.3"
daemonize = "0.4.1"
wry = "0.5.0"

