[package]
name = "lyra"
version = "0.1.1"
authors = ["dfontana <dyfontana@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
include_dir = "0.6.0"
lazy_static = "1.4.0"
serde = "1.0.123"
serde_json = "1.0.64"
thiserror = "1.0.24"
tokio = { version = "1.8.0", features = ["full"] }
tao = { git = "https://github.com/tauri-apps/tao", rev = "308411caeacc3b7c701d8d857964248a3411dfaa"}
wry = {git = "https://github.com/tauri-apps/wry", rev = "3e8585a394fd4d08633f46f34fde5dbb40b72e5e"}

[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", rev = "308411caeacc3b7c701d8d857964248a3411dfaa" }

